sources:
  - name: magicswapv2
    handler:
      graphql:
        endpoint: ${MAGICSWAPV2_API_URL}
documents:
  - "./app/**/*.graphql"
codegen:
  scalars:
    BigDecimal: string
    BigInt: string
    Bytes: string
