name: PR Checks
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate code
        run: pnpm run generate
        env:
          MAGICSWAPV2_API_URL: ${{ vars.MAGICSWAPV2_API_URL }}
      - name: Lint code
        run: pnpm run lint
      - name: Test code
        run: pnpm test
      - name: Check types
        run: pnpm run typecheck
      - name: Build code
        run: pnpm run build
