export const stakingContractAbi = [
  {
    type: "function",
    name: "accrueRewards",
    inputs: [{ name: "incentiveId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batch",
    inputs: [{ name: "datas", type: "bytes[]", internalType: "bytes[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimAllRewards",
    inputs: [
      { name: "incentiveIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [
      { name: "rewards", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRewards",
    inputs: [
      { name: "incentiveIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [
      { name: "rewards", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createIncentive",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "rewardToken", type: "address", internalType: "address" },
      { name: "rewardAmount", type: "uint112", internalType: "uint112" },
      { name: "startTime", type: "uint32", internalType: "uint32" },
      { name: "endTime", type: "uint32", internalType: "uint32" },
      { name: "isRewardRounded", type: "bool", internalType: "bool" },
    ],
    outputs: [
      { name: "incentiveId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "incentiveCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "incentives",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "rewardToken", type: "address", internalType: "address" },
      { name: "endTime", type: "uint32", internalType: "uint32" },
      { name: "isRewardRounded", type: "bool", internalType: "bool" },
      { name: "rewardPerLiquidity", type: "uint256", internalType: "uint256" },
      { name: "lastRewardTime", type: "uint32", internalType: "uint32" },
      { name: "rewardRemaining", type: "uint112", internalType: "uint112" },
      { name: "liquidityStaked", type: "uint112", internalType: "uint112" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rewardPerLiquidityLast",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "stakeAndSubscribeToIncentives",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint112", internalType: "uint112" },
      { name: "incentiveIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "transferExistingRewards", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stakeToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint112", internalType: "uint112" },
      { name: "transferExistingRewards", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscribeToIncentive",
    inputs: [{ name: "incentiveId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscribeToIncentives",
    inputs: [
      { name: "incentiveIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unstakeToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint112", internalType: "uint112" },
      { name: "transferExistingRewards", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unsubscribeFromIncentive",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "incentiveIndex", type: "uint256", internalType: "uint256" },
      { name: "ignoreRewards", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateIncentive",
    inputs: [
      { name: "incentiveId", type: "uint256", internalType: "uint256" },
      { name: "changeAmount", type: "int112", internalType: "int112" },
      { name: "newStartTime", type: "uint32", internalType: "uint32" },
      { name: "newEndTime", type: "uint32", internalType: "uint32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userStakes",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "liquidity", type: "uint112", internalType: "uint112" },
      {
        name: "subscribedIncentiveIds",
        type: "uint144",
        internalType: "uint144",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Claim",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IncentiveCreated",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "rewardToken",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "id", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "startTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IncentiveUpdated",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "changeAmount",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
      {
        name: "newStartTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newEndTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Stake",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Subscribe",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unstake",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unsubscribe",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadySubscribed", inputs: [] },
  { type: "error", name: "AlreadyUnsubscribed", inputs: [] },
  {
    type: "error",
    name: "BatchError",
    inputs: [{ name: "innerErorr", type: "bytes", internalType: "bytes" }],
  },
  { type: "error", name: "FullyPacked", inputs: [] },
  { type: "error", name: "IncentiveOverflow", inputs: [] },
  { type: "error", name: "InsufficientStakedAmount", inputs: [] },
  { type: "error", name: "InvalidIndex", inputs: [] },
  { type: "error", name: "InvalidInput", inputs: [] },
  { type: "error", name: "InvalidTimeFrame", inputs: [] },
  { type: "error", name: "NoToken", inputs: [] },
  { type: "error", name: "NonZero", inputs: [] },
  { type: "error", name: "NotStaked", inputs: [] },
  { type: "error", name: "NotSubscribed", inputs: [] },
  { type: "error", name: "OnlyCreator", inputs: [] },
] as const;
